### ISSUE TITLE
0.1.5 build seems to be based on 0.1.4 sources

### ISSUE THREAD

**Issue by SillyFreak** [andsala/svelte-persistent-store#16]
Hey, sorry to bear bad news again - I think something went wrong with the build for release 0.1.5. For example, this is `dist/chunk.PHCGGE36.js` ([npm](https://registry.npmjs.org/svelte-persistent-store/-/svelte-persistent-store-0.1.5.tgz)):

```js
"use strict";Object.defineProperty(exports, "__esModule", {value: true});

var _chunkFDWZTHUBjs = require('./chunk.FDWZTHUB.js');

// src/local.ts
const g = _chunkFDWZTHUBjs.generator.call(void 0, window.localStorage);
const readable = g.readable;
const writable = g.writable;
const derived = g.derived;
const get = g.get;






exports.readable = readable; exports.writable = writable; exports.derived = derived; exports.get = get;
```

The recent SSR fix is not in there, and the hashes in the file names suggest that this is the same code as 0.1.4 ([npm](https://registry.npmjs.org/svelte-persistent-store/-/svelte-persistent-store-0.1.4.tgz)).

Could you do a new release for this?

**Comment by andsala** [comment]
You are correct, it should be fixed now in v0.1.6
