### ISSUE TITLE
Error in import path with webpack

### ISSUE THREAD

**Issue by sdotb** [andsala/svelte-persistent-store#6]
Trying to import with:
`import { writable } from 'svelte-persistent-store/local';`
causes error:
Module not found: Error: Can't resolve 'svelte-persistent-store/local'

Looking in node_modules the code is inside "svelte-persistent-store/dist" directory
imported correctly with:
`import { writable } from 'svelte-persistent-store/dist/local';`

**Comment by andsala** [comment]
Thanks for the heads up
